name: Deploy Frontend to Server

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'yarn'
        cache-dependency-path: yarn.lock
        
    - name: Install dependencies with Yarn
      run: yarn install --frozen-lockfile --prefer-offline --silent
      
    - name: Create production environment file
      run: |
        cat > src/environments/environment.prod.ts << 'EOF'
        export const environment = {
          production: true,
          stage: 'production',
          apiUrl: '${{ secrets.FRONTEND_API_URL || 'https://api.bookingshub.es/api' }}',
          googleClientId: '${{ secrets.GOOGLE_CLIENT_ID || 'falta configurar' }}',
          googleMapsApiKey: '${{ secrets.GOOGLE_MAPS_API_KEY || 'falta configurar' }}',
          geocodeApiKey: '${{ secrets.GOOGLE_GEOCODE_API_KEY || 'falta configurar' }}',
          logLevel: 'error',
          version: '1.0.0',
          enableMocks: false
        };
        EOF
        
    - name: Build for production
      run: npm run build:prod
        
    - name: Create directories on server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT || 22 }}
        script: |          
          if [ -d "/var/www/bookings-hub-frontend/current" ]; then
            sudo mv /var/www/bookings-hub-frontend/current /var/www/bookings-hub-frontend/backups/backup_$(date +%Y%m%d_%H%M%S)
          fi
          
    - name: Upload files to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT || 22 }}
        source: "deploy/*"
        target: "/var/www/bookings-hub-frontend/current"
        strip_components: 2
        
    - name: Configure Nginx and finalize deployment
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT || 22 }}
        script: |          
          if sudo systemctl is-active --quiet nginx; then
            echo "Nginx está ejecutándose"
          else
            echo "Iniciando Nginx..."
            sudo systemctl start nginx
            sudo systemctl enable nginx
          fi
          
          cd /var/www/bookings-hub-frontend/backups
          if [ "$(ls -1 | wc -l)" -gt 5 ]; then
            ls -1t | tail -n +6 | xargs -r rm -rf
            echo "Backups antiguos limpiados"
          fi
          
          echo "Frontend deployment completed successfully!"